### ISSUE TITLE
Add styles to text printed out in the terminal for sync chat

### ISSUE THREAD

**Issue by delClg** [iiitl/JaT#4]
- Add appropriate styles to the text printed out by the CLI
- If possible code a separate class for implementing these styles to make it reusable in the future
- These styles should work in all mainstream terminals like windows PowerShell, bash, zsh, etc.

**Comment by N-Shar-ma** [comment]
Looking forward to this enhancement!

**Comment by delClg** [comment]
Should I document the class to print colored text in CONTRIBUTING.md or in a new README.md file in the class' package?

**Comment by N-Shar-ma** [comment]
For now keeping it in CONTRIBUTING.md sounds good!
