### ISSUE TITLE
Make walkie talkie chat print in terminal with colors using the ColorPrinter utility

### ISSUE THREAD

**Issue by N-Shar-ma** [iiitl/JaT#6]
Refer to the syncChat and use a similar color scheme for the walkie talkie chat system. (colors can be different - in fact, experimentation is encouraged - but the theme should be consistent, for example, the username color should differ from the message color like in SyncChat)

Additionally, put the 2 server and client files in a folder of their own called WalkieTalkie to clean up the project structure

**Comment by GAURCODER** [comment]
@N-Shar-ma Can you assign this issue to me?
